name: GitHub Actions Demo
run-name: ${{ github.actor }} estÃ¡ testando o GitHub Actions ğŸš€

on: [push]

jobs:
    Explorar-GitHub-Actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "ğŸ‰ O job for automÃ¡ticamente trigado pelo evento ${{ github.event_name }}."
            - run: echo "ğŸ§ Esse job estÃ¡ rodando em um servidor ${{ runner.os }} hospedado pelo GitHub!"
            - run: echo "ğŸ” O nome da branch Ã© ${{ github.ref }} e o seu repositÃ³rio Ã© ${{ github.repository }}."

            - name: Checa o cÃ³digo do repositÃ³rio
              uses: actions/checkout@v5

            - run: echo "ğŸ’¡ O repositÃ³rio ${{ github.repository }} foi clonado para o runner."
            - run: echo "ğŸ–¥ï¸ O workflow estÃ¡ agora pronto para testar o seu cÃ³digo no runner."
            
            - name: Lista os arquivos do repositÃ³rio
              run: |
                ls ${{ github.workspace }}
            
            - run: echo "ğŸ O status desse job Ã© ${{ job.status }}."

